version: "3.9"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "10.0"
          memory: "4g" 
  app:
    hostname: app-agent
    container_name: api_agent_ai
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2g"
volumes:
  ollama_data:
    name: ollama_data
networks:
  default:
    driver: bridge